### ISSUE TITLE
jsq is here!

### ISSUE THREAD

**Issue by jonathon-love** [jonathon-love/jsq#1]
hi @ejwagenmakers

just letting you know that we've made the jasp bayesian analyses available as a module for jamovi, called jsq. this is cool, because it will be making your analyses accessible to a broader audience.

we haven't put it in the jamovi library yet, but you can side-load it into the latest version (0.9.6.9), here are the links:

https://library.jamovi.org/modules/jsq_0.9.1-win64.jmo
https://library.jamovi.org/modules/jsq_0.9.1-macos.jmo

let us know if you have any feedback, or if you find any issues with it. we're pretty confident we've got all the references correct, for example.

we'd like to release in the next week or so.

cheers

**Comment by EJWagenmakers** [comment]
Hi Jonathon

That's great news!

Cheers,
E.J.
********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room G 0.29
University of Amsterdam, Nieuwe Achtergracht 129B
Letter: PO Box 15906, 1001 NK Amsterdam
Parcel: Valckenierstraat 59,  1018 XE Amsterdam

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Blog: bayesianspectacles.org
Email: EJ.Wagenmakers@gmail.com
Cell: (+31) 6 45626624

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by HRDudeness** [comment]
Any progress on the flatpak issues with JASPgraphs?

Cheers
Sven

**Comment by jonathon-love** [comment]
no, sorry not yet. you can start a new issue though.

cheers
