### ISSUE TITLE
Unable to compile jsq (flatpak)

### ISSUE THREAD

**Issue by HRDudeness** [jonathon-love/jsq#3]
jamovi 1.0.0 

```
jamovi compiler

jamovi found at /usr/bin/flatpak
wrote: bancova.h.R

Unable to compile 'bancova.u.yaml':
	The use of a 'VariableSupplier' control, with the property > populate: 'manual', requires an 'update' event handler to be assigned. Option: modelSupplier
```

When I'm trying to compile the recent master branch for the Linux flatpak version, I'm getting stuck with the above message.

**Comment by sjentsch** [comment]
I get the same error.
It happens with all compiler / jamovi versions I tested (1.0.4/1.04; 1.0.0 / 1.0.x; 1.0.4 / 0.9.x [several from repo.jamovi.org - incl. 0.9.0, the latest 0.9.6 and some intermediate).

**Comment by sjentsch** [comment]
I managed to solve the issue, even though I am relatively sure it is not the intended way of doing it and may lead to functionality issues.

Comment out the "populate: 'manual'" lines in the following files:
bancova.u.yaml
banova.u.yaml
banovarm.u.yaml
blinreg.u.yaml
bloglinear.u.yaml

**Comment by jonathon-love** [comment]
oh sorry guys, @dropmann will be able to advise you
